# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

checkconstraints <- function(data, neededpossiblehh) {
    .Call('NestedCategBayesImpute_checkconstraints', PACKAGE = 'NestedCategBayesImpute', data, neededpossiblehh)
}

households2individuals <- function(data) {
    .Call('NestedCategBayesImpute_households2individuals', PACKAGE = 'NestedCategBayesImpute', data)
}

groupcount <- function(g1, g2, n1, n2) {
    .Call('NestedCategBayesImpute_groupcount', PACKAGE = 'NestedCategBayesImpute', g1, g2, n1, n2)
}

groupcount1D <- function(g, n) {
    .Call('NestedCategBayesImpute_groupcount1D', PACKAGE = 'NestedCategBayesImpute', g, n)
}

samplehouseholds <- function(phi, w, pi, d, lambda, currrentbatch, nHouseholds, householdsize) {
    .Call('NestedCategBayesImpute_samplehouseholds', PACKAGE = 'NestedCategBayesImpute', phi, w, pi, d, lambda, currrentbatch, nHouseholds, householdsize)
}

samplezHH <- function(phi, data, w, pi, S, HHdata, lambda) {
    .Call('NestedCategBayesImpute_samplezHH', PACKAGE = 'NestedCategBayesImpute', phi, data, w, pi, S, HHdata, lambda)
}

samplezmember <- function(phi, data, w, zHH, serial) {
    .Call('NestedCategBayesImpute_samplezmember', PACKAGE = 'NestedCategBayesImpute', phi, data, w, zHH, serial)
}

