// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// checkconstraints
List checkconstraints(NumericMatrix data, int neededpossiblehh);
RcppExport SEXP SynthHousehold_checkconstraints(SEXP dataSEXP, SEXP neededpossiblehhSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type neededpossiblehh(neededpossiblehhSEXP);
    __result = Rcpp::wrap(checkconstraints(data, neededpossiblehh));
    return __result;
END_RCPP
}
// households2individuals
NumericMatrix households2individuals(NumericMatrix data);
RcppExport SEXP SynthHousehold_households2individuals(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    __result = Rcpp::wrap(households2individuals(data));
    return __result;
END_RCPP
}
// groupcount
NumericMatrix groupcount(NumericVector g1, NumericVector g2, int row, int col);
RcppExport SEXP SynthHousehold_groupcount(SEXP g1SEXP, SEXP g2SEXP, SEXP rowSEXP, SEXP colSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type g1(g1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type g2(g2SEXP);
    Rcpp::traits::input_parameter< int >::type row(rowSEXP);
    Rcpp::traits::input_parameter< int >::type col(colSEXP);
    __result = Rcpp::wrap(groupcount(g1, g2, row, col));
    return __result;
END_RCPP
}
// groupcount1D
NumericVector groupcount1D(NumericVector g, int groups);
RcppExport SEXP SynthHousehold_groupcount1D(SEXP gSEXP, SEXP groupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type g(gSEXP);
    Rcpp::traits::input_parameter< int >::type groups(groupsSEXP);
    __result = Rcpp::wrap(groupcount1D(g, groups));
    return __result;
END_RCPP
}
// prGpostFunc
NumericMatrix prGpostFunc(NumericMatrix phi_index, NumericMatrix lambda_index, NumericMatrix phi, NumericMatrix lambda, NumericMatrix omega, NumericVector pii, int FF, int SS, NumericVector cn_i);
RcppExport SEXP SynthHousehold_prGpostFunc(SEXP phi_indexSEXP, SEXP lambda_indexSEXP, SEXP phiSEXP, SEXP lambdaSEXP, SEXP omegaSEXP, SEXP piiSEXP, SEXP FFSEXP, SEXP SSSEXP, SEXP cn_iSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type phi_index(phi_indexSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lambda_index(lambda_indexSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pii(piiSEXP);
    Rcpp::traits::input_parameter< int >::type FF(FFSEXP);
    Rcpp::traits::input_parameter< int >::type SS(SSSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cn_i(cn_iSEXP);
    __result = Rcpp::wrap(prGpostFunc(phi_index, lambda_index, phi, lambda, omega, pii, FF, SS, cn_i));
    return __result;
END_RCPP
}
// prMpostFunc
NumericMatrix prMpostFunc(NumericMatrix phi_index, NumericMatrix phi, NumericMatrix omega, NumericVector rep_G, int FF, int SS);
RcppExport SEXP SynthHousehold_prMpostFunc(SEXP phi_indexSEXP, SEXP phiSEXP, SEXP omegaSEXP, SEXP rep_GSEXP, SEXP FFSEXP, SEXP SSSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type phi_index(phi_indexSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rep_G(rep_GSEXP);
    Rcpp::traits::input_parameter< int >::type FF(FFSEXP);
    Rcpp::traits::input_parameter< int >::type SS(SSSEXP);
    __result = Rcpp::wrap(prMpostFunc(phi_index, phi, omega, rep_G, FF, SS));
    return __result;
END_RCPP
}
// prEachComb02Func
NumericVector prEachComb02Func(NumericMatrix phi_index_02, NumericMatrix lambda_index_02, NumericMatrix phi, NumericMatrix lambda, NumericMatrix omega, NumericVector pii, int FF, int SS, NumericVector cn_i_02);
RcppExport SEXP SynthHousehold_prEachComb02Func(SEXP phi_index_02SEXP, SEXP lambda_index_02SEXP, SEXP phiSEXP, SEXP lambdaSEXP, SEXP omegaSEXP, SEXP piiSEXP, SEXP FFSEXP, SEXP SSSEXP, SEXP cn_i_02SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type phi_index_02(phi_index_02SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lambda_index_02(lambda_index_02SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pii(piiSEXP);
    Rcpp::traits::input_parameter< int >::type FF(FFSEXP);
    Rcpp::traits::input_parameter< int >::type SS(SSSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cn_i_02(cn_i_02SEXP);
    __result = Rcpp::wrap(prEachComb02Func(phi_index_02, lambda_index_02, phi, lambda, omega, pii, FF, SS, cn_i_02));
    return __result;
END_RCPP
}
// prGpost02Func
NumericMatrix prGpost02Func(NumericMatrix phi_index_02, NumericMatrix lambda_index_02, NumericMatrix phi, NumericMatrix lambda, NumericMatrix omega, NumericVector pii, int FF, int SS, NumericVector cn_i_02);
RcppExport SEXP SynthHousehold_prGpost02Func(SEXP phi_index_02SEXP, SEXP lambda_index_02SEXP, SEXP phiSEXP, SEXP lambdaSEXP, SEXP omegaSEXP, SEXP piiSEXP, SEXP FFSEXP, SEXP SSSEXP, SEXP cn_i_02SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type phi_index_02(phi_index_02SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lambda_index_02(lambda_index_02SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pii(piiSEXP);
    Rcpp::traits::input_parameter< int >::type FF(FFSEXP);
    Rcpp::traits::input_parameter< int >::type SS(SSSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cn_i_02(cn_i_02SEXP);
    __result = Rcpp::wrap(prGpost02Func(phi_index_02, lambda_index_02, phi, lambda, omega, pii, FF, SS, cn_i_02));
    return __result;
END_RCPP
}
// sampleXMiss02Func
NumericMatrix sampleXMiss02Func(NumericMatrix lambda_index_house_miss_02, NumericMatrix phi_index_struc_zero_pass_02, NumericMatrix lambda, NumericVector pii, NumericMatrix phi, NumericMatrix omega, NumericVector G_X_miss_02, NumericVector M_X_miss_02, int FF);
RcppExport SEXP SynthHousehold_sampleXMiss02Func(SEXP lambda_index_house_miss_02SEXP, SEXP phi_index_struc_zero_pass_02SEXP, SEXP lambdaSEXP, SEXP piiSEXP, SEXP phiSEXP, SEXP omegaSEXP, SEXP G_X_miss_02SEXP, SEXP M_X_miss_02SEXP, SEXP FFSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type lambda_index_house_miss_02(lambda_index_house_miss_02SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi_index_struc_zero_pass_02(phi_index_struc_zero_pass_02SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pii(piiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type G_X_miss_02(G_X_miss_02SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type M_X_miss_02(M_X_miss_02SEXP);
    Rcpp::traits::input_parameter< int >::type FF(FFSEXP);
    __result = Rcpp::wrap(sampleXMiss02Func(lambda_index_house_miss_02, phi_index_struc_zero_pass_02, lambda, pii, phi, omega, G_X_miss_02, M_X_miss_02, FF));
    return __result;
END_RCPP
}
// rcpp_hello
List rcpp_hello();
RcppExport SEXP SynthHousehold_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello());
    return __result;
END_RCPP
}
// samplehouseholds
NumericMatrix samplehouseholds(NumericMatrix phi, NumericMatrix w, NumericVector pi, NumericVector d, NumericMatrix lambda1, NumericMatrix lambda2, int currrentbatch, int nHouseholds, int householdsize);
RcppExport SEXP SynthHousehold_samplehouseholds(SEXP phiSEXP, SEXP wSEXP, SEXP piSEXP, SEXP dSEXP, SEXP lambda1SEXP, SEXP lambda2SEXP, SEXP currrentbatchSEXP, SEXP nHouseholdsSEXP, SEXP householdsizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pi(piSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< int >::type currrentbatch(currrentbatchSEXP);
    Rcpp::traits::input_parameter< int >::type nHouseholds(nHouseholdsSEXP);
    Rcpp::traits::input_parameter< int >::type householdsize(householdsizeSEXP);
    __result = Rcpp::wrap(samplehouseholds(phi, w, pi, d, lambda1, lambda2, currrentbatch, nHouseholds, householdsize));
    return __result;
END_RCPP
}
// samplezHH
List samplezHH(NumericMatrix phi, NumericMatrix data, NumericMatrix w, NumericVector pi, NumericVector S, NumericMatrix HHdata, NumericMatrix lambda1, NumericMatrix lambda2);
RcppExport SEXP SynthHousehold_samplezHH(SEXP phiSEXP, SEXP dataSEXP, SEXP wSEXP, SEXP piSEXP, SEXP SSEXP, SEXP HHdataSEXP, SEXP lambda1SEXP, SEXP lambda2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pi(piSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type S(SSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type HHdata(HHdataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type lambda2(lambda2SEXP);
    __result = Rcpp::wrap(samplezHH(phi, data, w, pi, S, HHdata, lambda1, lambda2));
    return __result;
END_RCPP
}
// samplezmember
NumericVector samplezmember(NumericMatrix phi, NumericMatrix data, NumericMatrix w, NumericVector zHH, NumericVector serial);
RcppExport SEXP SynthHousehold_samplezmember(SEXP phiSEXP, SEXP dataSEXP, SEXP wSEXP, SEXP zHHSEXP, SEXP serialSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type zHH(zHHSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type serial(serialSEXP);
    __result = Rcpp::wrap(samplezmember(phi, data, w, zHH, serial));
    return __result;
END_RCPP
}
