# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

checkconstraints <- function(data, neededpossiblehh) {
    .Call('SynthHousehold_checkconstraints', PACKAGE = 'SynthHousehold', data, neededpossiblehh)
}

households2individuals <- function(data) {
    .Call('SynthHousehold_households2individuals', PACKAGE = 'SynthHousehold', data)
}

groupcount <- function(g1, g2, n1, n2) {
    .Call('SynthHousehold_groupcount', PACKAGE = 'SynthHousehold', g1, g2, n1, n2)
}

groupcount1D <- function(g, groups) {
    .Call('SynthHousehold_groupcount1D', PACKAGE = 'SynthHousehold', g, groups)
}

samplehouseholds <- function(phi, w, pi, d, lambda1, lambda2, currrentbatch, nHouseholds, householdsize) {
    .Call('SynthHousehold_samplehouseholds', PACKAGE = 'SynthHousehold', phi, w, pi, d, lambda1, lambda2, currrentbatch, nHouseholds, householdsize)
}

samplezHH <- function(phi, data, w, pi, S, HHdata, lambda1, lambda2) {
    .Call('SynthHousehold_samplezHH', PACKAGE = 'SynthHousehold', phi, data, w, pi, S, HHdata, lambda1, lambda2)
}

samplezmember <- function(phi, data, w, zHH, serial) {
    .Call('SynthHousehold_samplezmember', PACKAGE = 'SynthHousehold', phi, data, w, zHH, serial)
}

